version: "3.3"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  memcached:
    image: memcached:1.5
    ports:
      - 11211
  redis:
    image: redis:4.0
    ports:
      - 6379
    volumes:
      - ./docker/redis/data:/data
  app:
    build:
      context: ./
      args:
        RAILS_ENV: development
    command:  /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
    depends_on:
      - database
      - memcached
      - redis
    volumes:
      - ./:/app:cached
      - empty:/app/public # ここをマウントさせないために書いている
    tty: true
    stdin_open: true

volumes:
  empty:
